title: CryptoML
description: >
  Cryptology. Machine Learning.
url: "/"
paginate:	3 # The number of posts to show per page on your homepage
name: "M. Bhargav Sri Venkatesh"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-sass-converter
