title: M. Bhargav Sri Venkatesh
description: >
  My space on internet.
url: "/"
paginate:	3 # The number of posts to show per page on your homepage
name: "SRI"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true


