title: M. Bhargav Sri Venkatesh
description: >
  My space on internet.
url: "/"
paginate:	3 # The number of posts to show per page on your homepage
name: "SRI"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true

Publications

"S-Box" Implementation of AES is NOT side-channel resistant
C Ashokkumar and Bholanath Roy and M Bhargav Sri Venkatesh and Bernard L Menezes
https://eprint.iacr.org/2018/1002

Design, Implementation and Performance Analysis of Highly Efficient Algorithms for AES Key Retrieval in Access-driven Cache-based Side Channel Attacks
Ashokkumar C and M. Bhargav Sri Venkatesh and Ravi Prakash Giri and Bernard Menezes
https://eprint.iacr.org/2017/896


Some reports and presentations

